/**
 * Markdown serializer — converts a PRDDocument to the rex/v1 markdown format.
 *
 * Output structure:
 *   1. YAML front-matter containing the entire PRDDocument (the canonical
 *      source of truth: schema, title, items tree).
 *   2. Auto-generated body for human reading: H1 title, then per-item
 *      heading + meta line + description in DFS pre-order.
 *
 * The body is regenerated on every serialize and is ignored by the parser.
 *
 * See packages/rex/docs/prd-markdown-schema.md for the authoritative spec.
 *
 * Field ordering inside each item mapping:
 *   id, level, title, status, priority, [remaining known fields a-z],
 *   [unknown fields a-z], description, children
 *
 * @module rex/store/markdown-serializer
 */

import type { PRDDocument, PRDItem, ItemLevel } from "../schema/index.js";

// ── Constants ────────────────────────────────────────────────────────────────

const LEVEL_TO_DEPTH: Record<ItemLevel, number> = {
  epic: 2,
  feature: 3,
  task: 4,
  subtask: 5,
};

const ORDERED_FIRST: ReadonlyArray<string> = ["id", "level", "title", "status", "priority"];

/** Known PRDItem fields. Used for stable alphabetical ordering after ORDERED_FIRST. */
const KNOWN_FIELDS = new Set([
  ...ORDERED_FIRST,
  "branch", "sourceFile", "tags", "source", "blockedBy",
  "startedAt", "completedAt", "endedAt", "activeIntervals",
  "acceptanceCriteria",
  "loe", "loeRationale", "loeConfidence",
  "tokenUsage", "duration",
  "resolutionType", "resolutionDetail", "failureReason",
  "requirements",
  "overrideMarker", "mergedProposals", "commits",
  "description", "children",
]);

const BODY_HEADER_COMMENT =
  "<!-- Auto-generated by rex. Edit the YAML front-matter above; body changes are not preserved. -->";

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Convert a PRDDocument to a rex/v1 markdown string.
 *
 * Output is deterministic: field ordering is fixed, values are canonically
 * quoted, and empty arrays are omitted (except Requirement.acceptanceCriteria).
 */
export function serializeDocument(doc: PRDDocument): string {
  const parts: string[] = [];

  // Front-matter
  parts.push("---");
  parts.push(`schema: ${quoteYamlString(doc.schema)}`);
  parts.push(`title: ${quoteYamlString(doc.title)}`);

  // Document-level extras (PRDDocument has [key: string]: unknown)
  const extraKeys = Object.keys(doc)
    .filter(k => k !== "schema" && k !== "title" && k !== "items")
    .sort();
  for (const key of extraKeys) {
    const v = (doc as Record<string, unknown>)[key];
    if (v === undefined || v === null) continue;
    if (Array.isArray(v) && v.length === 0) continue;
    const lines = emitYamlEntry(key, v, "");
    parts.push(...lines);
  }

  // Items sequence — dashes at indent 2, mapping body at indent 4
  if (doc.items.length === 0) {
    parts.push("items: []");
  } else {
    parts.push("items:");
    for (const item of doc.items) {
      parts.push(...emitItem(item, "    "));
    }
  }

  parts.push("---");
  parts.push("");
  parts.push(BODY_HEADER_COMMENT);
  parts.push("");
  parts.push(`# ${doc.title}`);
  parts.push("");

  for (const item of doc.items) {
    parts.push(...renderItemBody(item));
  }

  return parts.join("\n").trimEnd() + "\n";
}

// ── Item YAML emitter ─────────────────────────────────────────────────────────

/**
 * Emit a single item as YAML lines. The first emitted key is on a "- " sequence
 * marker line; subsequent keys are indented to `indent`.
 *
 * `indent` is the indent for the item's mapping body — the "- " marker itself
 * sits two columns to the left of `indent`.
 */
function emitItem(item: PRDItem, indent: string): string[] {
  const dashIndent = indent.slice(0, -2);
  const lines: string[] = [];

  const keysInOrder = orderedItemKeys(item);
  let first = true;

  for (const key of keysInOrder) {
    if (key === "children") continue; // emitted after, with recursion
    const value = (item as Record<string, unknown>)[key];
    if (value === undefined || value === null) continue;
    if (Array.isArray(value) && value.length === 0) continue;

    const prefix = first ? `${dashIndent}- ` : indent;
    first = false;
    lines.push(...emitYamlEntry(key, value, indent, prefix));
  }

  if (first) {
    // No fields rendered (shouldn't happen — id/title/level/status are required), emit empty marker
    lines.push(`${dashIndent}- {}`);
  }

  // Children recurse — child dashes 2 deeper than `children:` key, mapping 4 deeper
  if (item.children && item.children.length > 0) {
    lines.push(`${indent}children:`);
    for (const child of item.children) {
      lines.push(...emitItem(child, indent + "    "));
    }
  }

  return lines;
}

function orderedItemKeys(item: PRDItem): string[] {
  const all = new Set<string>(Object.keys(item));
  const ordered: string[] = [];

  for (const key of ORDERED_FIRST) {
    if (all.has(key)) {
      ordered.push(key);
      all.delete(key);
    }
  }

  // Remaining known fields, alphabetical (excluding ORDERED_FIRST, description, children)
  const knownRemaining = [...KNOWN_FIELDS]
    .filter(k => !ORDERED_FIRST.includes(k) && k !== "description" && k !== "children")
    .filter(k => all.has(k))
    .sort();
  for (const key of knownRemaining) {
    ordered.push(key);
    all.delete(key);
  }

  // Unknown fields, alphabetical
  const unknown = [...all]
    .filter(k => k !== "description" && k !== "children")
    .sort();
  for (const key of unknown) {
    ordered.push(key);
    all.delete(key);
  }

  // description and children at the end (description last simple field, children very last)
  if (all.has("description")) ordered.push("description");
  if (all.has("children")) ordered.push("children");

  return ordered;
}

// ── YAML emission ─────────────────────────────────────────────────────────────

/**
 * Emit a key-value YAML entry as one or more lines.
 *
 * `indent` is the indent applied to continuation lines (when the value is a
 * block-style mapping, sequence, or block scalar).
 *
 * `prefix` (optional) overrides the indent applied to the first line. Used by
 * `emitItem` so the first key of a sequence item sits on the "- " marker line.
 */
function emitYamlEntry(
  key: string,
  value: unknown,
  indent: string,
  prefix?: string,
): string[] {
  const firstPrefix = prefix ?? indent;

  if (value === undefined || value === null) return [];

  if (typeof value === "number" || typeof value === "boolean") {
    return [`${firstPrefix}${key}: ${value}`];
  }

  if (typeof value === "string") {
    if (shouldUseBlockScalar(value)) {
      const lines: string[] = [`${firstPrefix}${key}: |-`];
      const childIndent = indent + "  ";
      for (const line of value.split("\n")) {
        lines.push(line === "" ? "" : `${childIndent}${line}`);
      }
      return lines;
    }
    return [`${firstPrefix}${key}: ${quoteYamlString(value)}`];
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return [];
    const lines: string[] = [`${firstPrefix}${key}:`];
    for (const item of value) {
      lines.push(...emitSequenceItem(item, indent + "  "));
    }
    return lines;
  }

  if (typeof value === "object") {
    const body = emitMapping(value as Record<string, unknown>, indent + "  ");
    if (body.length === 0) return [];
    return [`${firstPrefix}${key}:`, ...body];
  }

  return [];
}

function emitMapping(obj: Record<string, unknown>, indent: string): string[] {
  const out: string[] = [];
  const keys = Object.keys(obj).sort();
  for (const key of keys) {
    const value = obj[key];
    if (value === undefined || value === null) continue;
    if (Array.isArray(value) && value.length === 0) continue;
    out.push(...emitYamlEntry(key, value, indent));
  }
  return out;
}

/**
 * Emit a sequence item. Objects: first key on the "- " line, continuation
 * fields indented past the marker. Scalars: "- value".
 */
function emitSequenceItem(item: unknown, indent: string): string[] {
  if (item === undefined || item === null) return [];

  if (typeof item === "number" || typeof item === "boolean") {
    return [`${indent}- ${item}`];
  }

  if (typeof item === "string") {
    if (shouldUseBlockScalar(item)) {
      // Rare: multi-line string in a sequence. Use block scalar.
      const lines: string[] = [`${indent}- |-`];
      const childIndent = indent + "  ";
      for (const line of item.split("\n")) {
        lines.push(line === "" ? "" : `${childIndent}${line}`);
      }
      return lines;
    }
    return [`${indent}- ${quoteYamlString(item)}`];
  }

  if (typeof item === "object" && !Array.isArray(item)) {
    const obj = item as Record<string, unknown>;
    const entries = orderedSequenceObjectEntries(obj);
    if (entries.length === 0) return [`${indent}- {}`];

    const dashIndent = indent;
    const contIndent = indent + "  ";
    const lines: string[] = [];
    let first = true;

    for (const [key, value] of entries) {
      if (value === undefined || value === null) continue;
      // Special case: Requirement.acceptanceCriteria must always be written, even empty
      const isRequiredAcceptanceCriteria = key === "acceptanceCriteria" && Array.isArray(value);
      if (Array.isArray(value) && value.length === 0 && !isRequiredAcceptanceCriteria) continue;
      if (Array.isArray(value) && value.length === 0 && isRequiredAcceptanceCriteria) {
        const prefix = first ? `${dashIndent}- ` : contIndent;
        lines.push(`${prefix}${key}: []`);
        first = false;
        continue;
      }

      const prefix = first ? `${dashIndent}- ` : contIndent;
      lines.push(...emitYamlEntry(key, value, contIndent, prefix));
      first = false;
    }

    if (first) return [`${indent}- {}`];
    return lines;
  }

  return [];
}

function orderedSequenceObjectEntries(obj: Record<string, unknown>): Array<[string, unknown]> {
  // ActiveInterval shape: start first, then end (if present), then alphabetical extras.
  // CommitAttribution shape: hash, author, authorEmail, timestamp, then message (if present).
  // Requirement / generic objects: id and title first, then alphabetical.
  const keys = Object.keys(obj);

  if (keys.includes("start")) {
    const ordered: Array<[string, unknown]> = [["start", obj["start"]]];
    if (keys.includes("end")) ordered.push(["end", obj["end"]]);
    for (const k of keys.filter(k => k !== "start" && k !== "end").sort()) {
      ordered.push([k, obj[k]]);
    }
    return ordered;
  }

  // CommitAttribution: hash, author, authorEmail, timestamp, message (optional)
  if (keys.includes("hash") && keys.includes("timestamp")) {
    const ordered: Array<[string, unknown]> = [["hash", obj["hash"]]];
    const fieldsAfterHash = ["author", "authorEmail", "timestamp"];
    for (const k of fieldsAfterHash) {
      if (keys.includes(k)) {
        ordered.push([k, obj[k]]);
      }
    }
    // Remaining fields (like message) in alphabetical order
    for (const k of keys.filter(k => !["hash", ...fieldsAfterHash].includes(k)).sort()) {
      ordered.push([k, obj[k]]);
    }
    return ordered;
  }

  const ordered: Array<[string, unknown]> = [];
  const remaining = new Set(keys);
  for (const k of ["id", "title"]) {
    if (remaining.has(k)) {
      ordered.push([k, obj[k]]);
      remaining.delete(k);
    }
  }
  for (const k of [...remaining].sort()) {
    ordered.push([k, obj[k]]);
  }
  return ordered;
}

// ── Block scalar / quoting ────────────────────────────────────────────────────

function shouldUseBlockScalar(s: string): boolean {
  // Multi-line strings are easier to read as block scalars. Keep single lines
  // as quoted/plain strings even when long.
  return s.includes("\n");
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ISO_TS_RE = /^\d{4}-\d{2}-\d{2}T/;
const YAML_BOOL_NULL_RE = /^(null|true|false|yes|no|on|off|~)$/i;
const LOOKS_LIKE_NUMBER_RE = /^[-+]?(\d+\.?\d*|\.\d+)([eE][-+]?\d+)?$/;
const YAML_INDICATOR_START_RE = /^[:{}&*#[\]|>%@`!?,]/;

function mustQuoteYamlString(s: string): boolean {
  if (s === "") return true;
  if (UUID_RE.test(s)) return true;
  if (ISO_TS_RE.test(s)) return true;
  if (YAML_BOOL_NULL_RE.test(s)) return true;
  if (LOOKS_LIKE_NUMBER_RE.test(s)) return true;
  if (YAML_INDICATOR_START_RE.test(s)) return true;
  if (s.includes(": ")) return true;
  if (/ #/.test(s)) return true;
  if (s !== s.trim()) return true;
  if (s.includes("\n") || s.includes("\r")) return true;
  if (s.includes("\\") || s.includes('"')) return true;
  return false;
}

function quoteYamlString(s: string): string {
  if (!mustQuoteYamlString(s)) return s;
  const escaped = s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return `"${escaped}"`;
}

// ── Body rendering (auto-generated, presentational) ───────────────────────────

function renderItemBody(item: PRDItem): string[] {
  const lines: string[] = [];
  const depth = LEVEL_TO_DEPTH[item.level] ?? 2;
  const hashes = "#".repeat(depth);

  lines.push(`${hashes} ${item.title}`);
  lines.push(`*${renderMetaLine(item)}*`);
  lines.push("");

  if (item.description && item.description.trim() !== "") {
    lines.push(item.description);
    lines.push("");
  }

  if (item.children && item.children.length > 0) {
    for (const child of item.children) {
      lines.push(...renderItemBody(child));
    }
  }

  return lines;
}

function renderMetaLine(item: PRDItem): string {
  const parts: string[] = [item.level, item.status];
  if (item.priority) parts.push(`priority: ${item.priority}`);
  if (item.startedAt) parts.push(`started ${formatDate(item.startedAt)}`);
  if (item.completedAt) parts.push(`completed ${formatDate(item.completedAt)}`);
  else if (item.endedAt) parts.push(`ended ${formatDate(item.endedAt)}`);
  if (item.tags && item.tags.length > 0) parts.push(`tags: ${item.tags.join(", ")}`);
  return parts.join(" · ");
}

function formatDate(iso: string): string {
  // "2026-01-10T09:00:00.000Z" → "2026-01-10"
  const m = /^(\d{4}-\d{2}-\d{2})/.exec(iso);
  return m ? m[1] : iso;
}
