/**
 * Validates Codex integration: AGENTS.md, .codex/config.toml generation, skill
 * writing, and the setupCodexIntegration() orchestration function.
 *
 * Tests cover:
 *   1. renderAgentsMd() produces correct markdown from manifest data
 *   2. renderCodexConfigToml() produces valid TOML with correct structure
 *   3. setupCodexIntegration() writes config, skills, and AGENTS.md to disk
 *   4. codex-integration.js imports from assistant-assets/ (no inline defs)
 *   5. --no-codex flag suppresses Codex artifact generation during init
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach } from "vitest";
import { readFileSync, existsSync, mkdtempSync, rmSync } from "fs";
import { execFileSync } from "node:child_process";
import { mkdtemp, rm, writeFile, chmod } from "node:fs/promises";
import { join } from "path";
import { tmpdir } from "os";
import {
  getMcpServers,
  getSkillNames,
  renderCodexConfigToml,
  renderAgentsMd,
  renderClaudeMd,
} from "../../assistant-assets/index.js";
import {
  setupCodexIntegration,
  printCodexSetupSummary,
} from "../../codex-integration.js";

const ROOT = join(import.meta.dirname, "../..");
const isWin = process.platform === "win32";
const PATH_SEP = isWin ? ";" : ":";
const CLI_PATH = join(ROOT, "cli.js");

// ── Helpers ─────────────────────────────────────────────────────────────────

/** Fake CLI resolver for tests — returns a deterministic path. */
function fakeResolveCli(pkgDir, _npmName) {
  return join(ROOT, pkgDir, "dist/cli/index.js");
}

async function writeFakeBinary(filePath, { stdout = "", stderrLine = "", exitCode = 0 } = {}) {
  if (isWin) {
    const cmdPath = filePath + ".cmd";
    const lines = ["@echo off"];
    if (stderrLine) lines.push(`echo ${stderrLine} 1>&2`);
    if (stdout) lines.push(`echo ${stdout}`);
    if (exitCode !== 0) lines.push(`exit /b ${exitCode}`);
    await writeFile(cmdPath, lines.join("\r\n") + "\r\n");
    return cmdPath;
  }
  const lines = ["#!/bin/sh"];
  if (stderrLine) lines.push(`echo '${stderrLine}' 1>&2`);
  if (stdout) lines.push(`echo '${stdout}'`);
  if (exitCode !== 0) lines.push(`exit ${exitCode}`);
  await writeFile(filePath, lines.join("\n") + "\n");
  await chmod(filePath, 0o755);
  return filePath;
}

function run(args, opts = {}) {
  return execFileSync("node", [CLI_PATH, ...args], {
    encoding: "utf-8",
    timeout: 20000,
    stdio: "pipe",
    ...opts,
  });
}

// ── renderAgentsMd() ────────────────────────────────────────────────────────

describe("renderAgentsMd", () => {
  const content = renderAgentsMd();
  const servers = getMcpServers();
  const skillNames = getSkillNames();

  it("produces non-empty string", () => {
    expect(content.length).toBeGreaterThan(0);
  });

  it("starts with generated-file HTML comment", () => {
    expect(content).toMatch(/^<!-- Generated by ndx init/);
    expect(content).toContain("do not edit manually");
  });

  it("has an n-dx heading", () => {
    expect(content).toContain("# n-dx");
  });

  it("includes shared project guidance sections", () => {
    expect(content).toContain("## Packages");
    expect(content).toContain("## Monorepo Structure");
    expect(content).toContain("### Architecture");
    expect(content).toContain("## Command Aliases");
    expect(content).toContain("## n-dx Orchestration Commands");
    expect(content).toContain("## Direct Tool Access");
    expect(content).toContain("## Key Files");
  });

  it("excludes Claude-specific deep sections from shared guidance", () => {
    expect(content).not.toContain("zone fragility governance");
    expect(content).not.toContain("Injection seam registry");
    expect(content).not.toContain("Concurrency contract");
    expect(content).not.toContain("<!-- ADDENDUM -->");
  });

  it("excludes shared guidance MCP and Workflow sections (replaced by manifest-derived)", () => {
    // Should not contain the shared guidance's HTTP transport setup
    expect(content).not.toContain("claude mcp add --transport http");
    // Should not contain the shared guidance's Development Workflow steps
    expect(content).not.toContain("## Development Workflow");
  });

  it("includes a Workflow section", () => {
    expect(content).toContain("## Workflow");
    expect(content).toContain("get_next_task");
    expect(content).toContain("update_task_status");
    expect(content).toContain("append_log");
  });

  it("includes an Available Skills section listing all manifest skills", () => {
    expect(content).toContain("## Available Skills");
    for (const name of skillNames) {
      expect(content).toContain(`**${name}**`);
    }
  });

  it("includes skill descriptions from the manifest", () => {
    // Verify at least one description appears
    expect(content).toContain("Analyze the codebase and propose PRD updates");
  });

  it("includes an MCP Servers section for each manifest server", () => {
    expect(content).toContain("## MCP Servers");
    for (const name of Object.keys(servers)) {
      expect(content).toContain(`### ${name}`);
    }
  });

  it("lists read tools for each server", () => {
    for (const [, descriptor] of Object.entries(servers)) {
      for (const tool of descriptor.tools.read) {
        expect(content).toContain(`\`${tool}\``);
      }
    }
  });

  it("lists write tools for each server", () => {
    for (const [, descriptor] of Object.entries(servers)) {
      for (const tool of descriptor.tools.write) {
        expect(content).toContain(`\`${tool}\``);
      }
    }
  });

  it("includes a When to Use Each Server section", () => {
    expect(content).toContain("## When to Use Each Server");
    expect(content).toContain("**Rex**");
    expect(content).toContain("**SourceVision**");
  });

  it("includes Codex Troubleshooting section", () => {
    expect(content).toContain("## Codex Troubleshooting");
    expect(content).toContain("Malformed Codex output");
  });

  it("uses bare tool names (no mcp__ prefix for Codex)", () => {
    // Codex uses bare tool names, not mcp__server__ prefixed
    expect(content).not.toContain("mcp__rex__");
    expect(content).not.toContain("mcp__sourcevision__");
  });

  it("is idempotent — calling twice returns identical content", () => {
    const second = renderAgentsMd();
    expect(content).toBe(second);
  });

  it("references .rex/workflow.md", () => {
    expect(content).toContain(".rex/workflow.md");
  });

  it("references .agents/skills/", () => {
    expect(content).toContain(".agents/skills/");
  });

  it("references .codex/config.toml", () => {
    expect(content).toContain(".codex/config.toml");
  });
});

// ── renderCodexConfigToml() ─────────────────────────────────────────────────

describe("renderCodexConfigToml", () => {
  const servers = getMcpServers();
  const serverNames = Object.keys(servers);

  it("produces non-empty string", () => {
    const content = renderCodexConfigToml("/project", fakeResolveCli);
    expect(content.length).toBeGreaterThan(0);
  });

  it("starts with generated-file header comment", () => {
    const content = renderCodexConfigToml("/project", fakeResolveCli);
    expect(content).toMatch(/^# Generated by ndx init/);
    expect(content).toContain("do not edit manually");
  });

  it("contains a [mcp_servers.<name>] section for each manifest server", () => {
    const content = renderCodexConfigToml("/project", fakeResolveCli);
    for (const name of serverNames) {
      expect(content).toContain(`[mcp_servers.${name}]`);
    }
  });

  it("each server section has command = \"node\"", () => {
    const content = renderCodexConfigToml("/project", fakeResolveCli);
    const sections = content.split("[mcp_servers.").slice(1);
    for (const section of sections) {
      expect(section).toContain('command = "node"');
    }
  });

  it("each server section has args with entrypoint, mcp command, and project dir", () => {
    const content = renderCodexConfigToml("/project", fakeResolveCli);
    for (const [name, descriptor] of Object.entries(servers)) {
      const expectedEntry = join(ROOT, descriptor.package, "dist/cli/index.js");
      expect(content).toContain(expectedEntry);
      expect(content).toContain(descriptor.mcpCommand);
      expect(content).toContain("/project");
    }
  });

  it("args are formatted as a valid TOML inline array", () => {
    const content = renderCodexConfigToml("/project", fakeResolveCli);
    // Each args line should match: args = ["...", "...", "..."]
    const argsLines = content.split("\n").filter((l) => l.startsWith("args"));
    expect(argsLines.length).toBe(serverNames.length);
    for (const line of argsLines) {
      expect(line).toMatch(/^args = \[".+", ".+", ".+"\]$/);
    }
  });

  it("escapes backslashes in Windows-style paths", () => {
    const winResolver = () => "C:\\Users\\dev\\packages\\rex\\dist\\cli\\index.js";
    const content = renderCodexConfigToml("C:\\project", winResolver);
    // Backslashes should be escaped in TOML strings
    expect(content).toContain("C:\\\\Users\\\\dev");
    expect(content).toContain("C:\\\\project");
  });
});

// ── setupCodexIntegration() ─────────────────────────────────────────────────

describe("setupCodexIntegration", () => {
  let tmpDir;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "ndx-codex-integration-"));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("creates .codex/config.toml", () => {
    setupCodexIntegration(tmpDir);
    expect(existsSync(join(tmpDir, ".codex", "config.toml"))).toBe(true);
  });

  it("config.toml contains MCP server definitions", () => {
    setupCodexIntegration(tmpDir);
    const content = readFileSync(join(tmpDir, ".codex", "config.toml"), "utf-8");
    const servers = getMcpServers();
    for (const name of Object.keys(servers)) {
      expect(content).toContain(`[mcp_servers.${name}]`);
    }
  });

  it("config.toml uses stdio transport (command + args, no url)", () => {
    setupCodexIntegration(tmpDir);
    const content = readFileSync(join(tmpDir, ".codex", "config.toml"), "utf-8");
    expect(content).toContain('command = "node"');
    expect(content).not.toContain("url =");
    expect(content).not.toContain("http://");
  });

  it("writes Codex skill files to .agents/skills/", () => {
    setupCodexIntegration(tmpDir);
    const skillNames = getSkillNames();
    for (const name of skillNames) {
      expect(existsSync(join(tmpDir, ".agents", "skills", name, "SKILL.md"))).toBe(true);
    }
  });

  it("creates AGENTS.md in the project root", () => {
    setupCodexIntegration(tmpDir);
    expect(existsSync(join(tmpDir, "AGENTS.md"))).toBe(true);
  });

  it("AGENTS.md contains generated content from manifest", () => {
    setupCodexIntegration(tmpDir);
    const content = readFileSync(join(tmpDir, "AGENTS.md"), "utf-8");
    expect(content).toContain("# n-dx");
    expect(content).toContain("## Available Skills");
    expect(content).toContain("## MCP Servers");
    // Must use bare tool names for Codex (no mcp__ prefix)
    expect(content).not.toContain("mcp__rex__");
  });

  it("returns correct result shape", () => {
    const result = setupCodexIntegration(tmpDir);

    expect(result).toHaveProperty("config");
    expect(result.config.written).toBe(true);
    expect(result.config.serverCount).toBe(Object.keys(getMcpServers()).length);

    expect(result).toHaveProperty("skills");
    expect(result.skills.written).toBe(getSkillNames().length);

    expect(result).toHaveProperty("agents");
    expect(result.agents.written).toBe(true);
    expect(result.agents.path).toContain("AGENTS.md");
  });

  it("is idempotent — running twice produces the same output", () => {
    setupCodexIntegration(tmpDir);
    const firstToml = readFileSync(join(tmpDir, ".codex", "config.toml"), "utf-8");
    const firstAgents = readFileSync(join(tmpDir, "AGENTS.md"), "utf-8");

    setupCodexIntegration(tmpDir);
    const secondToml = readFileSync(join(tmpDir, ".codex", "config.toml"), "utf-8");
    const secondAgents = readFileSync(join(tmpDir, "AGENTS.md"), "utf-8");

    expect(firstToml).toBe(secondToml);
    expect(firstAgents).toBe(secondAgents);
  });
});

// ── codex-integration.js source validation ──────────────────────────────────

describe("codex-integration.js uses canonical source", () => {
  const src = readFileSync(join(ROOT, "codex-integration.js"), "utf-8");

  it("imports from assistant-assets/", () => {
    expect(src).toContain('from "./assistant-assets/index.js"');
  });

  it("imports writeVendorSkills from the render contract", () => {
    expect(src).toContain("writeVendorSkills");
  });

  it("imports renderCodexConfigToml from the render contract", () => {
    expect(src).toContain("renderCodexConfigToml");
  });

  it("imports renderAgentsMd from the render contract", () => {
    expect(src).toContain("renderAgentsMd");
  });

  it("does not contain inline skill definitions", () => {
    if (/^const SKILLS\s*=\s*\{/m.test(src)) {
      expect.fail(
        "codex-integration.js contains an inline SKILLS object.\n" +
        "It should import skills from assistant-assets/ instead.",
      );
    }
  });

  it("does not contain hardcoded TOML strings", () => {
    // The TOML content should be generated by renderCodexConfigToml, not hardcoded
    if (/\[mcp_servers\.rex\]/.test(src)) {
      expect.fail(
        "codex-integration.js contains hardcoded TOML server definitions.\n" +
        "It should use renderCodexConfigToml() from assistant-assets/ instead.",
      );
    }
  });
});

// ── CLI integration: --no-codex flag ─────────────────────────────────────────

describe("ndx init --no-codex", () => {
  let tmpDir;

  beforeEach(async () => {
    tmpDir = await mkdtemp(join(tmpdir(), "ndx-init-nocodex-"));
  });

  afterEach(async () => {
    await rm(tmpDir, { recursive: true, force: true });
  });

  it("skips Codex artifacts when --no-codex is passed", async () => {
    const binDir = await mkdtemp(join(tmpdir(), "ndx-init-bin-nocodex-"));
    try {
      await writeFakeBinary(join(binDir, "codex"), { stdout: "ok" });

      const output = run(
        ["init", "--provider=codex", "--no-codex", tmpDir],
        {
          env: {
            ...process.env,
            PATH: `${binDir}${PATH_SEP}${process.env.PATH ?? ""}`,
          },
        },
      );

      expect(output).toContain("Codex");
      expect(output).toContain("skipped");
      expect(existsSync(join(tmpDir, ".codex", "config.toml"))).toBe(false);
      expect(existsSync(join(tmpDir, "AGENTS.md"))).toBe(false);
    } finally {
      await rm(binDir, { recursive: true, force: true });
    }
  });

  it("generates Codex artifacts by default (no --no-codex)", async () => {
    const binDir = await mkdtemp(join(tmpdir(), "ndx-init-bin-codex-default-"));
    try {
      await writeFakeBinary(join(binDir, "codex"), { stdout: "ok" });

      const output = run(
        ["init", "--provider=codex", tmpDir],
        {
          env: {
            ...process.env,
            PATH: `${binDir}${PATH_SEP}${process.env.PATH ?? ""}`,
          },
        },
      );

      expect(existsSync(join(tmpDir, ".codex", "config.toml"))).toBe(true);
      expect(existsSync(join(tmpDir, ".agents", "skills"))).toBe(true);
      expect(existsSync(join(tmpDir, "AGENTS.md"))).toBe(true);
      // Summary line should show AGENTS.md and MCP server count
      expect(output).toMatch(/Codex\s+AGENTS\.md, \d+ skills, \d+ MCP servers/);
    } finally {
      await rm(binDir, { recursive: true, force: true });
    }
  });
});
