/**
 * CONTEXT.md generator — dense, structured summary optimized for
 * Claude context windows. Uses XML-style markers for reliable parsing.
 */

import type {
  Manifest,
  Inventory,
  Imports,
  Classifications,
  Zones,
  Components,
  DetectedFrameworks,
} from "../schema/index.js";
import { buildClassificationMap } from "./classify.js";
import { deriveNextSteps } from "./next-steps.js";
import { SUPPORTED_LANGUAGES } from "./framework-support.js";

export function generateContext(
  manifest: Manifest,
  inventory: Inventory,
  imports: Imports,
  zones: Zones,
  components?: Components | null,
  classifications?: Classifications | null,
  frameworks?: DetectedFrameworks | null,
): string {
  const lines: string[] = [];
  const projectName = manifest.targetPath.split("/").pop() || "project";

  lines.push(`# ${projectName} — CONTEXT`);
  lines.push("");
  lines.push("<!-- Machine-readable codebase context. Generated by Sourcevision. -->");
  lines.push("<!-- When using this context: group related items together, separate unrelated concerns. -->");
  lines.push("");

  // ── Architecture ────────────────────────────────────────────────────────

  lines.push("<architecture>");
  lines.push("");

  const gitParts = [manifest.gitBranch, manifest.gitSha?.slice(0, 7)].filter(Boolean);
  lines.push(`Project: ${projectName}`);
  if (gitParts.length) lines.push(`Git: ${gitParts.join(" @ ")}`);
  lines.push(`Files: ${inventory.summary.totalFiles}, Lines: ${inventory.summary.totalLines}`);

  const topLangs = Object.entries(inventory.summary.byLanguage)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 5)
    .map(([lang, count]) => `${lang}(${count})`)
    .join(" ");
  lines.push(`Languages: ${topLangs}`);

  const describedZones = zones.zones.filter((z) => z.description).length;
  lines.push(`Zones: ${zones.zones.length}, Described: ${describedZones}`);
  lines.push(`Import edges: ${imports.summary.totalEdges}, External packages: ${imports.summary.totalExternal}`);
  if (imports.summary.circularCount > 0) {
    lines.push(`Circulars: ${imports.summary.circularCount}`);
  }
  lines.push("");
  lines.push("</architecture>");
  lines.push("");

  // ── Frameworks ────────────────────────────────────────────────────────

  if (frameworks && frameworks.frameworks.length > 0) {
    lines.push("<frameworks>");
    lines.push("");

    for (const fw of frameworks.frameworks) {
      const conf = fw.confidence >= 0.8 ? "high" : fw.confidence >= 0.5 ? "medium" : "low";
      const root = fw.projectRoot !== "." ? ` root=${fw.projectRoot}` : "";
      lines.push(`${fw.name} [${fw.category}] lang=${fw.language} confidence=${conf}(${fw.confidence})${root}`);
    }

    // Supported language tiers
    lines.push("");
    const tier1 = SUPPORTED_LANGUAGES.filter((l) => l.tier === 1).map((l) => l.name);
    const tier2 = SUPPORTED_LANGUAGES.filter((l) => l.tier === 2).map((l) => l.name);
    lines.push(`Analysis support: Tier 1 (full): ${tier1.join(", ")} | Tier 2 (detect-only): ${tier2.join(", ")}`);

    lines.push("");
    lines.push("</frameworks>");
    lines.push("");
  }

  // ── Zones ───────────────────────────────────────────────────────────────

  const archetypeMap = buildClassificationMap(classifications);

  if (zones.zones.length > 0) {
    lines.push("<zones>");
    lines.push("");

    for (const zone of zones.zones) {
      const metrics = `coh=${zone.cohesion.toFixed(2)} coup=${zone.coupling.toFixed(2)}`;
      lines.push(`[${zone.id}] ${zone.name} (${zone.files.length} files, ${metrics})`);
      if (zone.description) {
        lines.push(`  ${zone.description}`);
      }
      // Condensed file list with archetype labels
      const fileList = zone.files.slice(0, 10).map((f) => {
        const arch = archetypeMap.get(f);
        return arch ? `${f} [${arch}]` : f;
      }).join(", ");
      const more = zone.files.length > 10 ? ` +${zone.files.length - 10}` : "";
      lines.push(`  files: ${fileList}${more}`);
    }

    if (zones.unzoned.length > 0) {
      lines.push(`[unzoned] ${zones.unzoned.length} files: ${zones.unzoned.slice(0, 5).join(", ")}${zones.unzoned.length > 5 ? " ..." : ""}`);
    }

    lines.push("");
    lines.push("Detailed zone context: .sourcevision/zones/{id}/context.md");

    lines.push("");
    lines.push("</zones>");
    lines.push("");
  }

  // ── Import Graph (adjacency format) ─────────────────────────────────────

  if (imports.summary.mostImported.length > 0) {
    lines.push("<imports>");
    lines.push("");

    // Show most-imported files with their importers
    lines.push("Most imported:");
    for (const item of imports.summary.mostImported.slice(0, 10)) {
      const importers = imports.edges
        .filter((e) => e.to === item.path)
        .map((e) => e.from)
        .slice(0, 5);
      const more = imports.edges.filter((e) => e.to === item.path).length > 5
        ? ` +${imports.edges.filter((e) => e.to === item.path).length - 5}`
        : "";
      lines.push(`  ${item.path} ← ${importers.join(", ")}${more}`);
    }

    if (imports.summary.circulars.length > 0) {
      lines.push("");
      lines.push("Circular chains:");
      for (const circ of imports.summary.circulars.slice(0, 3)) {
        lines.push(`  ${circ.cycle.join(" → ")}`);
      }
    }

    lines.push("");
    lines.push("</imports>");
    lines.push("");
  }

  // ── Routes ──────────────────────────────────────────────────────────────

  const hasClientRoutes = components && components.routeModules.length > 0;
  const hasServerRoutes = components && components.serverRoutes.length > 0;

  if (hasClientRoutes || hasServerRoutes) {
    lines.push("<routes>");
    lines.push("");

    if (hasClientRoutes) {
      lines.push(`Route modules: ${components.summary.totalRouteModules}`);
      lines.push(`Components: ${components.summary.totalComponents}`);
      lines.push(`Usage edges: ${components.summary.totalUsageEdges}`);

      if (components.routeTree.length > 0) {
        lines.push("");
        printTree(components.routeTree, lines, 0);
      }

      const conventions = Object.entries(components.summary.routeConventions);
      if (conventions.length > 0) {
        lines.push("");
        lines.push(`Conventions: ${conventions.map(([k, v]) => `${k}(${v})`).join(" ")}`);
      }
    }

    if (hasServerRoutes) {
      if (hasClientRoutes) lines.push("");
      lines.push(`Server routes: ${components.summary.totalServerRoutes} endpoints in ${components.serverRoutes.length} handler(s)`);
      lines.push("");
      for (const group of components.serverRoutes) {
        const handler = group.handler ? ` (${group.handler})` : "";
        lines.push(`${group.prefix}${handler} — ${group.file}`);
        for (const r of group.routes) {
          lines.push(`  ${r.method.padEnd(7)} ${r.path}`);
        }
      }
    }

    lines.push("");
    lines.push("</routes>");
    lines.push("");
  }

  // ── Findings (warning + critical only) ──────────────────────────────────

  const findings = (zones.findings ?? []).filter(
    (f) => f.severity === "warning" || f.severity === "critical"
  );
  if (findings.length > 0) {
    lines.push("<findings>");
    lines.push("");

    for (const f of findings.slice(0, 15)) {
      const scope = f.scope !== "global" ? ` [${f.scope}]` : "";
      lines.push(`[${f.severity}] ${f.text}${scope}`);
    }
    if (findings.length > 15) {
      lines.push(`... +${findings.length - 15} more`);
    }

    lines.push("");
    lines.push("</findings>");
    lines.push("");
  }

  // ── Next Steps ──────────────────────────────────────────────────────

  // Only show high and medium priority next steps in the dense context
  // format — low-priority items are noise for LLMs consuming CONTEXT.md.
  const nextSteps = deriveNextSteps(zones).filter(
    (s) => s.priority !== "low"
  );
  if (nextSteps.length > 0) {
    lines.push("<next-steps>");
    lines.push("");

    for (const step of nextSteps.slice(0, 15)) {
      const zone = zones.zones.find((z) => z.id === step.scope);
      const files = zone ? zone.files.slice(0, 3).join(", ") : "";
      lines.push(`[${step.priority}] ${step.title}`);
      if (files) {
        lines.push(`  files: ${files}`);
      }
      lines.push(`  category: ${step.category}`);
    }

    lines.push("");
    lines.push("</next-steps>");
    lines.push("");
  }

  return lines.join("\n");
}

function printTree(
  nodes: import("../schema/v1.js").RouteTreeNode[],
  lines: string[],
  depth: number
): void {
  for (const node of nodes) {
    const indent = "  ".repeat(depth);
    lines.push(`${indent}${node.routePattern} (${node.file})`);
    printTree(node.children, lines, depth + 1);
  }
}
