/**
 * Configuration constants and helpers for AI enrichment passes.
 */

import type {
  Zone,
  ZoneCrossing,
  Finding,
  FindingType,
} from "../schema/index.js";

// ── Constants ────────────────────────────────────────────────────────────────

// ── Batch mode constants ─────────────────────────────────────────────────────

export const ZONES_PER_BATCH = 5;
export const MAX_CONCURRENT_BATCHES = 1;

// ── Per-zone mode constants ──────────────────────────────────────────────────

/** Max concurrent zone enrichments in per-zone mode */
export const MAX_CONCURRENT_ZONES = 3;
/** Max files to include in single-zone prompt (higher than batch since context is smaller) */
export const PER_ZONE_MAX_FILES = 15;
/** Max boundary crossings to include in single-zone prompt */
export const PER_ZONE_MAX_CROSSINGS = 20;

// ── Pass configuration ───────────────────────────────────────────────────────

/** Configuration for each enrichment pass — maps to expected finding types */
export interface PassConfig {
  focus: string;
  expectedTypes: FindingType[];
}

export const PASS_CONFIGS: PassConfig[] = [
  { focus: "", expectedTypes: ["observation"] }, // pass 0 = algorithmic only
  {
    focus: `For each zone, provide:
1. A meaningful, descriptive name (not generic like "utilities" or "misc" — reflect the zone's actual domain role)
2. A one-sentence description of the zone's architectural purpose
3. 2-3 actionable observations about its role and quality

Severity guide: most observations are "info". Flag zones with low cohesion (<0.4) or high coupling (>0.6) as "warning".`,
    expectedTypes: ["observation"],
  },
  {
    focus: `Focus on relationships BETWEEN zones:
- What architectural patterns exist? (e.g. layered architecture, hub-and-spoke, circular dependencies)
- Where are the clean boundaries? Which zone pairs have well-defined interfaces?
- Where are the leaky abstractions? Which zones reach into each other's internals?

Severity guide: clean relationships are "info". Leaky abstractions or missing interfaces are "warning". Circular dependencies between zones are "critical".`,
    expectedTypes: ["pattern", "relationship"],
  },
  {
    focus: `Identify concrete problems:
- Tight coupling that should be broken (zones that depend on each other's internal details)
- Missing abstraction layers (zones communicating through implementation details instead of interfaces)
- Files that belong in a different zone based on their actual purpose
- Zones that should be split (too many unrelated concerns) or merged (too few files, same concern)

Severity guide: misplaced files are "warning". Missing abstractions and tight coupling are "warning" or "critical" based on blast radius.`,
    expectedTypes: ["anti-pattern"],
  },
  {
    focus: `Look for subtle patterns and improvement opportunities:
- Naming inconsistencies (files/exports that don't match the zone's naming conventions)
- Risk areas: zones with BOTH high coupling AND low cohesion are fragile — flag them
- Implicit conventions that should be documented or enforced
- Specific refactoring opportunities with clear before/after descriptions

Severity guide: naming inconsistencies are "info". Risk areas and urgent refactors are "warning".`,
    expectedTypes: ["suggestion"],
  },
];

export function getPassConfig(pass: number, existingFindingsCount?: number): PassConfig {
  if (pass < PASS_CONFIGS.length) return PASS_CONFIGS[pass];
  // Pass 5+ = meta-evaluation
  return {
    focus: `You are reviewing all ${existingFindingsCount ?? 0} findings from previous analysis passes. Each finding is annotated with its source pass and detection method.

IMPORTANT CONSTRAINTS:
- Findings from "pass 0: automated heuristic" are generated by deterministic code analysis (edge counting, metric thresholds). Do NOT escalate their severity unless corroborated by MULTIPLE independent findings pointing to the same root cause.
- Do NOT generate specific file decomposition suggestions unless the underlying metric exceeds 2x its detection threshold.
- When referencing metrics from existing findings, preserve the exact numeric values as written. Do not round, estimate, or modify measurement values from heuristic findings.

Your tasks:

1. SEVERITY REASSESSMENT: Re-evaluate each finding's severity based on cumulative evidence.
   - Upgrade to "critical" only if multiple independent findings point to the same root cause.
   - Downgrade to "info" if a finding seemed concerning in isolation but is actually fine in context.
   - Never upgrade a lone automated heuristic finding to "critical" without corroboration.

2. META-PATTERNS: Look across ALL findings for higher-order patterns not captured individually.
   - Are there systemic issues (e.g. all zones have the same coupling problem)?
   - Are there architecture-level concerns (e.g. no clear layering, everything depends on everything)?

3. ACTIONABLE SUGGESTIONS: Convert vague observations into specific refactoring steps.
   - Each suggestion should name concrete files/zones and describe what to move/extract/merge.
   - Prefer small, incremental changes over big-bang rewrites.
   - Only suggest file decomposition when metrics are significantly above thresholds (2x+).

4. CONTRADICTIONS: Flag findings that contradict each other and explain which one is correct.

Return updated severity assignments, new meta-findings, and improved suggestions.`,
    expectedTypes: ["suggestion", "anti-pattern", "pattern"],
  };
}

// ── Prompt builders ──────────────────────────────────────────────────────────

/** Pass descriptions for meta-evaluation annotations. */
const PASS_LABELS: Record<number, string> = {
  0: "pass 0: automated heuristic",
  1: "pass 1: LLM zone naming + initial observations",
  2: "pass 2: LLM cross-zone relationships",
  3: "pass 3: LLM anti-pattern detection",
  4: "pass 4: LLM suggestions + risk areas",
};

/** Detection method labels for pass 0 findings, inferred from finding text. */
function detectMethod(f: Finding): string {
  if (f.pass !== 0) return "LLM analysis";
  const t = f.text.toLowerCase();
  if (t.startsWith("god function:")) return "call-graph: outgoing-call count";
  if (t.startsWith("tightly coupled modules:")) return "call-graph: cross-file edge count";
  if (t.includes("unused export")) return "call-graph: dead-export scan";
  if (t.startsWith("hub function:")) return "call-graph: fan-in (caller file count)";
  if (t.startsWith("fan-in hotspot:")) return "call-graph: fan-in (caller file count)";
  if (t.includes("cohesion") || t.includes("coupling")) return "zone metrics: cohesion/coupling";
  if (t.includes("entry point")) return "zone metrics: entry-point analysis";
  return "automated heuristic";
}

/** Format a finding line with source pass and detection method annotations. */
function formatAnnotatedFinding(f: Finding, index: number): string {
  const passLabel = PASS_LABELS[f.pass] ?? `pass ${f.pass}: LLM analysis`;
  const method = detectMethod(f);
  return `  ${index}: [${f.severity ?? "unset"}] (${f.type}) [source: ${passLabel}; method: ${method}] ${f.text}`;
}

/**
 * Build a meta-evaluation prompt that sends accumulated findings
 * instead of zone structure, for pass 5+.
 */
export function buildMetaPrompt(
  zones: Zone[],
  findings: Finding[],
  crossings: ZoneCrossing[],
): string {
  // Group findings by zone
  const findingsByZone = new Map<string, Finding[]>();
  const globalFindings: Finding[] = [];
  for (const f of findings) {
    if (f.scope === "global") {
      globalFindings.push(f);
    } else {
      let list = findingsByZone.get(f.scope);
      if (!list) { list = []; findingsByZone.set(f.scope, list); }
      list.push(f);
    }
  }

  const zonesSummary = zones.map((z) => {
    const zf = findingsByZone.get(z.id) ?? [];
    const findingsStr = zf.map((f, i) =>
      formatAnnotatedFinding(f, i)
    ).join("\n");
    return `Zone "${z.id}" (${z.name}, ${z.files.length} files, cohesion: ${z.cohesion}, coupling: ${z.coupling})\n${findingsStr || "  (no findings)"}`;
  }).join("\n\n");

  const globalStr = globalFindings.map((f, i) =>
    formatAnnotatedFinding(f, i)
  ).join("\n");

  return `META-EVALUATION: Review all ${findings.length} findings from previous analysis passes.

Zone Summaries with Findings:
${zonesSummary}

Global Findings:
${globalStr || "  (none)"}

Cross-zone crossings: ${crossings.length} total across ${new Set(crossings.map(c => c.fromZone + "\u2192" + c.toZone)).size} zone pairs.

IMPORTANT CONSTRAINTS:
- Findings annotated "pass 0: automated heuristic" come from deterministic code analysis (call-graph edge counting, zone metric thresholds). Do NOT escalate their severity unless corroborated by MULTIPLE independent findings pointing to the same root cause. A single heuristic finding alone is never sufficient evidence for "critical" severity.
- Do NOT generate specific file decomposition suggestions (e.g. "split X into Y and Z", "extract module from X") unless the underlying metric exceeds 2x its detection threshold. Vague heuristic signals do not justify concrete refactoring prescriptions.
- When referencing metrics from existing findings, preserve the exact numeric values as written. Do not round, estimate, or modify measurement values from heuristic findings.

Your tasks:
1. SEVERITY REASSESSMENT: Re-evaluate findings where severity should change based on cumulative evidence. Upgrade if multiple findings point to the same root cause. Downgrade if a finding seemed concerning in isolation but is fine in context. Remember: do not escalate heuristic-only findings without corroboration.
2. META-PATTERNS: Identify higher-order patterns across ALL findings (systemic issues, architectural concerns).
3. ACTIONABLE SUGGESTIONS: Convert vague observations into specific refactoring steps naming concrete files/zones. Only suggest file decomposition when metrics are significantly above thresholds (2x+).
4. CONTRADICTIONS: Flag findings that contradict each other and explain which is correct.

Each finding MUST include a "severity" field: "info" (informational), "warning" (should fix), or "critical" (must fix).

Respond with ONLY a JSON object (no markdown, no explanation):
{"severityUpdates":[{"findingIndex":0,"newSeverity":"warning"}],"zones":[{"id":"zone-id","newInsights":[],"findings":[{"type":"suggestion","scope":"zone-id","text":"...","severity":"warning"}]}],"insights":["meta-observation"],"findings":[{"type":"pattern","scope":"global","text":"...","severity":"info"}]}

Empty arrays are fine. Do NOT repeat existing findings.`;
}

// ── Attempt configuration ────────────────────────────────────────────────────

/** Compute attempt configs with timeouts that scale with file/zone count and pass complexity.
 *  When batching, pass the batch's file/zone counts (not totals).
 *  Pass 1 (naming + initial insights) is the heaviest — needs 1.5x the base.
 *  Minimum 5 minutes to avoid burning tokens on premature timeouts. */
export function computeAttemptConfigs(totalFiles: number, zoneCount: number, passNumber: number = 1) {
  const sizeBase = totalFiles * 400 + zoneCount * 5_000;
  const passMultiplier = passNumber === 1 ? 1.5 : 1;
  const base = Math.min(600_000, Math.max(480_000, Math.round(sizeBase * passMultiplier)));
  return [
    { maxFiles: 8, maxCrossings: 15, timeout: Math.min(base, 600_000) },
    { maxFiles: 3, maxCrossings: 8,  timeout: Math.min(Math.round(base * 1.3), 600_000) },
    { maxFiles: 0, maxCrossings: 5,  timeout: Math.min(Math.round(base * 1.6), 600_000) },
  ];
}

/** Compute attempt configs for per-zone enrichment (single zone at a time).
 *  Since we're only sending one zone, we can include more files and crossings.
 *  Shorter base timeout since context is smaller. */
export function computePerZoneAttemptConfigs(zoneFileCount: number, passNumber: number = 1) {
  const sizeBase = zoneFileCount * 600 + 10_000;
  const passMultiplier = passNumber === 1 ? 1.3 : 1;
  const base = Math.min(300_000, Math.max(120_000, Math.round(sizeBase * passMultiplier)));
  return [
    { maxFiles: PER_ZONE_MAX_FILES, maxCrossings: PER_ZONE_MAX_CROSSINGS, timeout: Math.min(base, 300_000) },
    { maxFiles: 8,  maxCrossings: 12, timeout: Math.min(Math.round(base * 1.3), 300_000) },
    { maxFiles: 3,  maxCrossings: 6,  timeout: Math.min(Math.round(base * 1.6), 300_000) },
  ];
}
