/**
 * llms.txt generator — structured Markdown summary of a codebase
 * for consumption by LLMs and AI tools.
 */

import type {
  Manifest,
  Inventory,
  Imports,
  Classifications,
  Zones,
  Components,
  DetectedFrameworks,
} from "../schema/index.js";
import { buildClassificationMap } from "./classify.js";
import { deriveNextSteps } from "./next-steps.js";
import { SUPPORTED_LANGUAGES, getFrameworkCapabilities } from "./framework-support.js";

export function generateLlmsTxt(
  manifest: Manifest,
  inventory: Inventory,
  imports: Imports,
  zones: Zones,
  components?: Components | null,
  classifications?: Classifications | null,
  frameworks?: DetectedFrameworks | null,
): string {
  const lines: string[] = [
    ...buildProjectIdentity(manifest, inventory, zones),
    ...buildTechnologyStack(frameworks),
    ...buildArchitectureZones(zones),
    ...buildKeyDependencies(imports),
    ...buildRouteStructure(components),
    ...buildFindings(zones),
    ...buildNextSteps(zones),
    ...buildFileInventory(inventory, zones, classifications),
    ...buildTooling(),
  ];

  return lines.join("\n");
}

// ── Section builders ──────────────────────────────────────────────────────

function buildProjectIdentity(manifest: Manifest, inventory: Inventory, zones: Zones): string[] {
  const lines: string[] = [];

  const projectName = manifest.targetPath.split("/").pop() || "project";
  lines.push(`# ${projectName}`);
  lines.push("");

  lines.push("> Codebase analysis generated by Sourcevision.");
  lines.push("> When using this document: group related items together and separate unrelated concerns.");
  lines.push("");

  const gitInfo = [manifest.gitBranch, manifest.gitSha?.slice(0, 7)]
    .filter(Boolean)
    .join(" @ ");

  lines.push("## Project Overview");
  lines.push("");
  lines.push(`- **Files**: ${inventory.summary.totalFiles}`);
  lines.push(`- **Lines of code**: ${inventory.summary.totalLines.toLocaleString()}`);

  const topLangs = Object.entries(inventory.summary.byLanguage)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 5)
    .map(([lang, count]) => `${lang} (${count})`)
    .join(", ");
  lines.push(`- **Languages**: ${topLangs}`);

  const describedZones = zones.zones.filter((z) => z.description).length;
  lines.push(`- **Zones**: ${zones.zones.length} (${describedZones} with descriptions)`);

  if (gitInfo) {
    lines.push(`- **Git**: ${gitInfo}`);
  }
  lines.push(`- **Analyzed**: ${manifest.analyzedAt}`);
  lines.push("");

  return lines;
}

function buildTechnologyStack(frameworks?: DetectedFrameworks | null): string[] {
  if (!frameworks || frameworks.frameworks.length === 0) return [];

  const lines: string[] = [];
  lines.push("## Technology Stack");
  lines.push("");

  lines.push("### Detected Frameworks");
  lines.push("");

  for (const fw of frameworks.frameworks) {
    const confLabel = fw.confidence >= 0.8 ? "high" : fw.confidence >= 0.5 ? "medium" : "low";
    const root = fw.projectRoot !== "." ? ` (root: \`${fw.projectRoot}\`)` : "";
    const caps = getFrameworkCapabilities(fw.id);
    lines.push(`- **${fw.name}** — ${fw.category}, ${fw.language}, confidence: ${confLabel} (${fw.confidence})${root}`);
    if (caps.length > 0) {
      lines.push(`  - Analysis capabilities: ${caps.join(", ")}`);
    }
  }
  lines.push("");

  // Supported languages section
  lines.push("### Supported Languages");
  lines.push("");

  const tier1 = SUPPORTED_LANGUAGES.filter((l) => l.tier === 1);
  const tier2 = SUPPORTED_LANGUAGES.filter((l) => l.tier === 2);

  lines.push("**Tier 1 (full analysis):** inventory, import graph, zone detection, route detection, framework detection");
  lines.push("");
  for (const lang of tier1) {
    lines.push(`- ${lang.name}`);
  }
  lines.push("");

  if (tier2.length > 0) {
    lines.push("**Tier 2 (detection only):** inventory and basic detection");
    lines.push("");
    for (const lang of tier2) {
      lines.push(`- ${lang.name}`);
    }
    lines.push("");
  }

  return lines;
}

function buildArchitectureZones(zones: Zones): string[] {
  if (zones.zones.length === 0) return [];

  const lines: string[] = [];
  lines.push("## Architecture Zones");
  lines.push("");

  for (const zone of zones.zones) {
    lines.push(`### ${zone.name} (\`${zone.id}\`)`);
    lines.push("");
    if (zone.description) {
      lines.push(zone.description);
      lines.push("");
    }
    lines.push(`- Files: ${zone.files.length}`);
    lines.push(`- Cohesion: ${zone.cohesion.toFixed(2)}, Coupling: ${zone.coupling.toFixed(2)}`);
    if (zone.entryPoints.length > 0) {
      lines.push(`- Entry points: ${zone.entryPoints.slice(0, 5).join(", ")}${zone.entryPoints.length > 5 ? ` (+${zone.entryPoints.length - 5} more)` : ""}`);
    }
    lines.push(`- Detail: \`.sourcevision/zones/${zone.id.replace(/:/g, "-")}/context.md\``);
    lines.push("");
  }

  return lines;
}

function buildKeyDependencies(imports: Imports): string[] {
  const lines: string[] = [];

  lines.push("## Key Dependencies");
  lines.push("");

  if (imports.summary.mostImported.length > 0) {
    lines.push("### Most-Imported Files");
    lines.push("");
    for (const item of imports.summary.mostImported.slice(0, 10)) {
      lines.push(`- \`${item.path}\` (${item.count} imports)`);
    }
    lines.push("");
  }

  if (imports.external.length > 0) {
    const topExternal = [...imports.external]
      .sort((a, b) => b.importedBy.length - a.importedBy.length)
      .slice(0, 10);
    lines.push("### External Packages");
    lines.push("");
    for (const pkg of topExternal) {
      lines.push(`- \`${pkg.package}\` (used by ${pkg.importedBy.length} files)`);
    }
    lines.push("");
  }

  if (imports.summary.circularCount > 0) {
    lines.push("### Circular Dependencies");
    lines.push("");
    lines.push(`Found ${imports.summary.circularCount} circular dependency chain(s):`);
    lines.push("");
    for (const circ of imports.summary.circulars.slice(0, 5)) {
      lines.push(`- ${circ.cycle.map((f) => `\`${f}\``).join(" → ")}`);
    }
    if (imports.summary.circulars.length > 5) {
      lines.push(`- ... and ${imports.summary.circulars.length - 5} more`);
    }
    lines.push("");
  }

  return lines;
}

function buildRouteStructure(components?: Components | null): string[] {
  const hasClientRoutes = components && components.routeModules.length > 0;
  const hasServerRoutes = components && components.serverRoutes.length > 0;

  if (!hasClientRoutes && !hasServerRoutes) return [];

  const lines: string[] = [];
  lines.push("## Route Structure");
  lines.push("");

  if (hasClientRoutes) {
    if (components.routeTree.length > 0) {
      lines.push("### Route Tree");
      lines.push("");
      lines.push("```");
      printRouteTree(components.routeTree, lines, 0);
      lines.push("```");
      lines.push("");
    }

    lines.push("### Convention Exports");
    lines.push("");
    for (const [kind, count] of Object.entries(components.summary.routeConventions)) {
      lines.push(`- ${kind}: ${count} modules`);
    }
    lines.push("");
  }

  if (hasServerRoutes) {
    lines.push("### Server API Routes");
    lines.push("");
    for (const group of components.serverRoutes) {
      const handler = group.handler ? ` (${group.handler})` : "";
      lines.push(`**${group.prefix}**${handler} — \`${group.file}\``);
      lines.push("");
      lines.push("```");
      for (const r of group.routes) {
        lines.push(`${r.method.padEnd(7)} ${r.path}`);
      }
      lines.push("```");
      lines.push("");
    }
  }

  if (components && components.summary.totalComponents > 0) {
    lines.push(`### Components: ${components.summary.totalComponents} total, ${components.summary.totalUsageEdges} usage edges`);
    lines.push("");
    if (components.summary.mostUsedComponents.length > 0) {
      lines.push("Most used:");
      for (const comp of components.summary.mostUsedComponents.slice(0, 10)) {
        lines.push(`- \`${comp.name}\` in \`${comp.file}\` (${comp.usageCount} uses)`);
      }
      lines.push("");
    }
  }

  return lines;
}

function buildFindings(zones: Zones): string[] {
  const findings = zones.findings ?? [];
  if (findings.length === 0) return [];

  const lines: string[] = [];
  lines.push("## Findings");
  lines.push("");

  // Group by type
  const byType = new Map<string, typeof findings>();
  for (const f of findings) {
    if (!byType.has(f.type)) byType.set(f.type, []);
    byType.get(f.type)!.push(f);
  }

  const typeOrder = ["anti-pattern", "pattern", "relationship", "observation", "suggestion"];
  for (const type of typeOrder) {
    const group = byType.get(type);
    if (!group?.length) continue;

    lines.push(`### ${type.charAt(0).toUpperCase() + type.slice(1)}s`);
    lines.push("");
    for (const f of group.slice(0, 10)) {
      const sev = f.severity ? ` [${f.severity}]` : "";
      const scope = f.scope !== "global" ? ` (${f.scope})` : "";
      lines.push(`- ${f.text}${sev}${scope}`);
    }
    if (group.length > 10) {
      lines.push(`- ... and ${group.length - 10} more`);
    }
    lines.push("");
  }

  return lines;
}

function buildNextSteps(zones: Zones): string[] {
  const nextSteps = deriveNextSteps(zones);
  if (nextSteps.length === 0) return [];

  const lines: string[] = [];
  lines.push("## Next Steps");
  lines.push("");
  lines.push("Prioritized work items derived from analysis:");
  lines.push("");

  const byPriority = { high: [] as typeof nextSteps, medium: [] as typeof nextSteps, low: [] as typeof nextSteps };
  for (const step of nextSteps) {
    byPriority[step.priority].push(step);
  }

  for (const [priority, steps] of Object.entries(byPriority)) {
    if (steps.length === 0) continue;
    lines.push(`### ${priority.charAt(0).toUpperCase() + priority.slice(1)} Priority`);
    lines.push("");
    for (const step of steps.slice(0, 10)) {
      const zone = zones.zones.find((z) => z.id === step.scope);
      const files = zone ? zone.files.slice(0, 3).map((f) => `\`${f}\``).join(", ") : "";
      lines.push(`1. **${step.title}**`);
      if (files) {
        lines.push(`   Files: ${files}`);
      }
      lines.push("");
    }
  }

  return lines;
}

function buildFileInventory(inventory: Inventory, zones: Zones, classifications?: Classifications | null): string[] {
  const lines: string[] = [];

  lines.push("## File Inventory");
  lines.push("");

  // Build zone lookup
  const fileToZone = new Map<string, string>();
  for (const zone of zones.zones) {
    for (const file of zone.files) {
      fileToZone.set(file, zone.id);
    }
  }

  const archetypeMap = buildClassificationMap(classifications);

  lines.push("| Path | Role | Archetype | Zone |");
  lines.push("|------|------|-----------|------|");
  for (const file of inventory.files) {
    const zone = fileToZone.get(file.path) ?? "";
    const archetype = archetypeMap.get(file.path) ?? "";
    lines.push(`| \`${file.path}\` | ${file.role} | ${archetype} | ${zone} |`);
  }
  lines.push("");

  return lines;
}

function buildTooling(): string[] {
  return [
    "## Tooling",
    "",
    "This project uses n-dx for codebase analysis (Sourcevision) and requirement",
    "tracking (Rex). MCP tools are available for interactive access to analysis",
    "data and PRD management. Skills available: /plan, /status, /capture,",
    "/zone, /work, /configure.",
    "",
  ];
}

// ── Shared helpers ────────────────────────────────────────────────────────

function printRouteTree(nodes: import("../schema/v1.js").RouteTreeNode[], lines: string[], depth: number): void {
  for (const node of nodes) {
    const indent = "  ".repeat(depth);
    lines.push(`${indent}${node.routePattern} → ${node.file}`);
    printRouteTree(node.children, lines, depth + 1);
  }
}
