/**
 * llms.txt generator — structured Markdown summary of a codebase
 * for consumption by LLMs and AI tools.
 */

import type {
  Manifest,
  Inventory,
  Imports,
  Zones,
  Components,
} from "../schema/index.js";
import { deriveNextSteps } from "./next-steps.js";

export function generateLlmsTxt(
  manifest: Manifest,
  inventory: Inventory,
  imports: Imports,
  zones: Zones,
  components?: Components | null
): string {
  const lines: string[] = [];

  // ── Project Identity ────────────────────────────────────────────────────

  const projectName = manifest.targetPath.split("/").pop() || "project";
  lines.push(`# ${projectName}`);
  lines.push("");

  lines.push("> Codebase analysis generated by Sourcevision");
  lines.push("");

  const gitInfo = [manifest.gitBranch, manifest.gitSha?.slice(0, 7)]
    .filter(Boolean)
    .join(" @ ");

  lines.push("## Project Overview");
  lines.push("");
  lines.push(`- **Files**: ${inventory.summary.totalFiles}`);
  lines.push(`- **Lines of code**: ${inventory.summary.totalLines.toLocaleString()}`);

  const topLangs = Object.entries(inventory.summary.byLanguage)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 5)
    .map(([lang, count]) => `${lang} (${count})`)
    .join(", ");
  lines.push(`- **Languages**: ${topLangs}`);

  if (gitInfo) {
    lines.push(`- **Git**: ${gitInfo}`);
  }
  lines.push(`- **Analyzed**: ${manifest.analyzedAt}`);
  lines.push("");

  // ── Architecture Zones ──────────────────────────────────────────────────

  if (zones.zones.length > 0) {
    lines.push("## Architecture Zones");
    lines.push("");

    for (const zone of zones.zones) {
      lines.push(`### ${zone.name} (\`${zone.id}\`)`);
      lines.push("");
      if (zone.description) {
        lines.push(zone.description);
        lines.push("");
      }
      lines.push(`- Files: ${zone.files.length}`);
      lines.push(`- Cohesion: ${zone.cohesion.toFixed(2)}, Coupling: ${zone.coupling.toFixed(2)}`);
      if (zone.entryPoints.length > 0) {
        lines.push(`- Entry points: ${zone.entryPoints.slice(0, 5).join(", ")}${zone.entryPoints.length > 5 ? ` (+${zone.entryPoints.length - 5} more)` : ""}`);
      }
      lines.push("");
    }
  }

  // ── Key Dependencies ──────────────────────────────────────────────────

  lines.push("## Key Dependencies");
  lines.push("");

  if (imports.summary.mostImported.length > 0) {
    lines.push("### Most-Imported Files");
    lines.push("");
    for (const item of imports.summary.mostImported.slice(0, 10)) {
      lines.push(`- \`${item.path}\` (${item.count} imports)`);
    }
    lines.push("");
  }

  if (imports.external.length > 0) {
    const topExternal = [...imports.external]
      .sort((a, b) => b.importedBy.length - a.importedBy.length)
      .slice(0, 10);
    lines.push("### External Packages");
    lines.push("");
    for (const pkg of topExternal) {
      lines.push(`- \`${pkg.package}\` (used by ${pkg.importedBy.length} files)`);
    }
    lines.push("");
  }

  if (imports.summary.circularCount > 0) {
    lines.push("### Circular Dependencies");
    lines.push("");
    lines.push(`Found ${imports.summary.circularCount} circular dependency chain(s):`);
    lines.push("");
    for (const circ of imports.summary.circulars.slice(0, 5)) {
      lines.push(`- ${circ.cycle.map((f) => `\`${f}\``).join(" → ")}`);
    }
    if (imports.summary.circulars.length > 5) {
      lines.push(`- ... and ${imports.summary.circulars.length - 5} more`);
    }
    lines.push("");
  }

  // ── Route Structure ───────────────────────────────────────────────────

  if (components && components.routeModules.length > 0) {
    lines.push("## Route Structure");
    lines.push("");

    if (components.routeTree.length > 0) {
      lines.push("### Route Tree");
      lines.push("");
      lines.push("```");
      printRouteTree(components.routeTree, lines, 0);
      lines.push("```");
      lines.push("");
    }

    lines.push("### Convention Exports");
    lines.push("");
    for (const [kind, count] of Object.entries(components.summary.routeConventions)) {
      lines.push(`- ${kind}: ${count} modules`);
    }
    lines.push("");

    if (components.summary.totalComponents > 0) {
      lines.push(`### Components: ${components.summary.totalComponents} total, ${components.summary.totalUsageEdges} usage edges`);
      lines.push("");
      if (components.summary.mostUsedComponents.length > 0) {
        lines.push("Most used:");
        for (const comp of components.summary.mostUsedComponents.slice(0, 10)) {
          lines.push(`- \`${comp.name}\` in \`${comp.file}\` (${comp.usageCount} uses)`);
        }
        lines.push("");
      }
    }
  }

  // ── Findings ──────────────────────────────────────────────────────────

  const findings = zones.findings ?? [];
  if (findings.length > 0) {
    lines.push("## Findings");
    lines.push("");

    // Group by type
    const byType = new Map<string, typeof findings>();
    for (const f of findings) {
      if (!byType.has(f.type)) byType.set(f.type, []);
      byType.get(f.type)!.push(f);
    }

    const typeOrder = ["anti-pattern", "pattern", "relationship", "observation", "suggestion"];
    for (const type of typeOrder) {
      const group = byType.get(type);
      if (!group?.length) continue;

      lines.push(`### ${type.charAt(0).toUpperCase() + type.slice(1)}s`);
      lines.push("");
      for (const f of group.slice(0, 10)) {
        const sev = f.severity ? ` [${f.severity}]` : "";
        const scope = f.scope !== "global" ? ` (${f.scope})` : "";
        lines.push(`- ${f.text}${sev}${scope}`);
      }
      if (group.length > 10) {
        lines.push(`- ... and ${group.length - 10} more`);
      }
      lines.push("");
    }
  }

  // ── Next Steps ──────────────────────────────────────────────────────

  const nextSteps = deriveNextSteps(zones);
  if (nextSteps.length > 0) {
    lines.push("## Next Steps");
    lines.push("");
    lines.push("Prioritized work items derived from analysis:");
    lines.push("");

    const byPriority = { high: [] as typeof nextSteps, medium: [] as typeof nextSteps, low: [] as typeof nextSteps };
    for (const step of nextSteps) {
      byPriority[step.priority].push(step);
    }

    for (const [priority, steps] of Object.entries(byPriority)) {
      if (steps.length === 0) continue;
      lines.push(`### ${priority.charAt(0).toUpperCase() + priority.slice(1)} Priority`);
      lines.push("");
      for (const step of steps.slice(0, 10)) {
        const zone = zones.zones.find((z) => z.id === step.scope);
        const files = zone ? zone.files.slice(0, 3).map((f) => `\`${f}\``).join(", ") : "";
        lines.push(`1. **${step.title}**`);
        if (files) {
          lines.push(`   Files: ${files}`);
        }
        lines.push("");
      }
    }
  }

  // ── File Inventory ────────────────────────────────────────────────────

  lines.push("## File Inventory");
  lines.push("");

  // Build zone lookup
  const fileToZone = new Map<string, string>();
  for (const zone of zones.zones) {
    for (const file of zone.files) {
      fileToZone.set(file, zone.id);
    }
  }

  lines.push("| Path | Role | Zone |");
  lines.push("|------|------|------|");
  for (const file of inventory.files) {
    const zone = fileToZone.get(file.path) ?? "";
    lines.push(`| \`${file.path}\` | ${file.role} | ${zone} |`);
  }
  lines.push("");

  return lines.join("\n");
}

function printRouteTree(nodes: import("../schema/v1.js").RouteTreeNode[], lines: string[], depth: number): void {
  for (const node of nodes) {
    const indent = "  ".repeat(depth);
    lines.push(`${indent}${node.routePattern} → ${node.file}`);
    printRouteTree(node.children, lines, depth + 1);
  }
}
