/**
 * Per-zone output emitter — writes zone-scoped context and summary files
 * to .sourcevision/zones/{zone-id}/.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type {
  Inventory,
  Imports,
  Zones,
  Zone,
  ZoneCrossing,
  Finding,
  ZoneSummary,
} from "../schema/index.js";
import { toCanonicalJSON } from "../util/sort.js";

/** Generate context.md content for a single zone. */
export function generateZoneContext(
  zone: Zone,
  inventory: Inventory,
  imports: Imports,
  zones: Zones
): string {
  const lines: string[] = [];
  const fileSet = new Set(zone.files);

  lines.push(`# ${zone.name} — Zone Context`);
  lines.push("");
  lines.push("<!-- Per-zone context generated by Sourcevision. -->");
  lines.push("");

  // ── Zone header ──
  lines.push("<zone>");
  lines.push("");
  lines.push(`Zone: ${zone.name} (\`${zone.id}\`)`);
  lines.push(`Files: ${zone.files.length}, Cohesion: ${zone.cohesion.toFixed(2)}, Coupling: ${zone.coupling.toFixed(2)}`);
  if (zone.description) {
    lines.push(`Description: ${zone.description}`);
  }
  if (zone.entryPoints.length > 0) {
    lines.push(`Entry points: ${zone.entryPoints.join(", ")}`);
  }

  // Line count from inventory
  const zoneLineCount = inventory.files
    .filter((f) => fileSet.has(f.path))
    .reduce((sum, f) => sum + f.lineCount, 0);
  lines.push(`Lines: ${zoneLineCount}`);
  lines.push("");
  lines.push("</zone>");
  lines.push("");

  // ── Files ──
  lines.push("<files>");
  lines.push("");

  const zoneFiles = inventory.files.filter((f) => fileSet.has(f.path));
  for (const f of zoneFiles) {
    lines.push(`${f.path} (${f.language}, ${f.lineCount} lines, ${f.role})`);
  }

  lines.push("");
  lines.push("</files>");
  lines.push("");

  // ── Imports ──
  const internalEdges = imports.edges.filter(
    (e) => fileSet.has(e.from) && fileSet.has(e.to)
  );
  const boundaryCrossings = zones.crossings.filter(
    (c) => c.fromZone === zone.id || c.toZone === zone.id
  );

  if (internalEdges.length > 0 || boundaryCrossings.length > 0) {
    lines.push("<imports>");
    lines.push("");

    if (internalEdges.length > 0) {
      lines.push("Internal:");
      for (const e of internalEdges) {
        const symbols = e.symbols.length > 0 ? ` {${e.symbols.join(", ")}}` : "";
        lines.push(`  ${e.from} → ${e.to}${symbols}`);
      }
    }

    if (boundaryCrossings.length > 0) {
      // Group by target zone
      const outgoing = boundaryCrossings.filter((c) => c.fromZone === zone.id);
      const incoming = boundaryCrossings.filter((c) => c.toZone === zone.id);

      if (outgoing.length > 0) {
        lines.push("");
        lines.push("Outgoing (this zone → other zones):");
        const byTarget = groupBy(outgoing, (c) => c.toZone);
        for (const [targetZone, crossings] of sortedEntries(byTarget)) {
          const files = crossings.map((c) => `${c.from} → ${c.to}`);
          lines.push(`  → ${targetZone}: ${files.join("; ")}`);
        }
      }

      if (incoming.length > 0) {
        lines.push("");
        lines.push("Incoming (other zones → this zone):");
        const bySource = groupBy(incoming, (c) => c.fromZone);
        for (const [sourceZone, crossings] of sortedEntries(bySource)) {
          const files = crossings.map((c) => `${c.from} → ${c.to}`);
          lines.push(`  ← ${sourceZone}: ${files.join("; ")}`);
        }
      }
    }

    lines.push("");
    lines.push("</imports>");
    lines.push("");
  }

  // ── Findings ──
  const zoneFindings = (zones.findings ?? []).filter(
    (f) => f.scope === zone.id
  );
  if (zoneFindings.length > 0) {
    lines.push("<findings>");
    lines.push("");

    for (const f of zoneFindings) {
      const sev = f.severity ? ` [${f.severity}]` : "";
      lines.push(`[${f.type}]${sev} ${f.text}`);
    }

    lines.push("");
    lines.push("</findings>");
    lines.push("");
  }

  // ── Insights ──
  if (zone.insights && zone.insights.length > 0) {
    lines.push("<insights>");
    lines.push("");

    for (const insight of zone.insights) {
      lines.push(`- ${insight}`);
    }

    lines.push("");
    lines.push("</insights>");
    lines.push("");
  }

  // ── Sub-zones ──
  if (zone.subZones && zone.subZones.length > 0) {
    lines.push("<sub-zones>");
    lines.push("");

    lines.push(`This zone has ${zone.subZones.length} sub-zone(s):`);
    lines.push("");

    for (const subZone of zone.subZones) {
      lines.push(`- **${subZone.name}** (\`${subZone.id}\`): ${subZone.files.length} files, cohesion ${subZone.cohesion}, coupling ${subZone.coupling}`);
      if (subZone.subZones && subZone.subZones.length > 0) {
        lines.push(`  - Has ${subZone.subZones.length} nested sub-zone(s)`);
      }
    }

    lines.push("");
    lines.push("Detailed sub-zone context available in `zones/{sub-zone-id}/context.md`");
    lines.push("");
    lines.push("</sub-zones>");
    lines.push("");
  }

  return lines.join("\n");
}

/** Build summary.json for a single zone. */
export function buildZoneSummary(
  zone: Zone,
  inventory: Inventory
): ZoneSummary {
  const fileSet = new Set(zone.files);
  const lineCount = inventory.files
    .filter((f) => fileSet.has(f.path))
    .reduce((sum, f) => sum + f.lineCount, 0);

  return {
    id: zone.id,
    name: zone.name,
    description: zone.description,
    files: zone.files,
    entryPoints: zone.entryPoints,
    cohesion: zone.cohesion,
    coupling: zone.coupling,
    fileCount: zone.files.length,
    lineCount,
  };
}

/**
 * Emit per-zone output files to .sourcevision/zones/{zone-id}/.
 * Creates context.md and summary.json for each zone.
 * Recursively emits sub-zone outputs to nested directories.
 */
export function emitZoneOutputs(
  outputDir: string,
  inventory: Inventory,
  imports: Imports,
  zones: Zones
): void {
  const zonesDir = join(outputDir, "zones");

  for (const zone of zones.zones) {
    emitSingleZoneOutput(zonesDir, zone, inventory, imports, zones);
  }
}

/**
 * Emit output files for a single zone and its sub-zones recursively.
 */
function emitSingleZoneOutput(
  parentDir: string,
  zone: Zone,
  inventory: Inventory,
  imports: Imports,
  zones: Zones
): void {
  // Zone ID may contain "/" for nested zones (e.g., "hench/agent")
  // For nested zones, we use just the last segment as the directory name
  // Zone ID may contain ":" for sub-analysis zones (e.g., "packages-rex:cli")
  // Replace with "-" since ":" is not valid in Windows paths
  let dirName = zone.id.includes("/") ? zone.id.split("/").pop()! : zone.id;
  dirName = dirName.replace(/:/g, "-");
  const zoneDir = join(parentDir, dirName);
  mkdirSync(zoneDir, { recursive: true });

  const contextMd = generateZoneContext(zone, inventory, imports, zones);
  writeFileSync(join(zoneDir, "context.md"), contextMd);

  const summary = buildZoneSummary(zone, inventory);
  writeFileSync(join(zoneDir, "summary.json"), toCanonicalJSON(summary));

  // Recursively emit sub-zones
  if (zone.subZones && zone.subZones.length > 0) {
    const subZonesDir = join(zoneDir, "zones");
    for (const subZone of zone.subZones) {
      emitSingleZoneOutput(subZonesDir, subZone, inventory, imports, zones);
    }
  }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function groupBy<T>(items: T[], key: (item: T) => string): Map<string, T[]> {
  const map = new Map<string, T[]>();
  for (const item of items) {
    const k = key(item);
    let list = map.get(k);
    if (!list) {
      list = [];
      map.set(k, list);
    }
    list.push(item);
  }
  return map;
}

function sortedEntries<T>(map: Map<string, T>): [string, T][] {
  return [...map.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
}
