/**
 * Centralized PRD file I/O for web server routes.
 *
 * **Read path (loadPRDSync):**
 * Reads from the ephemeral cache file `.rex/.cache/prd.json`, which is
 * generated by `ndx start` at boot and kept in sync by a `prd.md` watcher.
 * Falls back to parsing `.rex/prd.md` directly when the cache is absent
 * (e.g. in tests that call `loadPRDSync` without starting the server).
 *
 * **Write path (savePRDSync):**
 * Serializes `doc` back to `.rex/prd.md` (the Markdown source of truth) and
 * atomically refreshes the cache file so subsequent `loadPRDSync` calls see
 * the update without waiting for the `prd.md` watcher to fire.
 *
 * **Why sync?** HTTP route handlers in the web server use synchronous patterns.
 * Rex's canonical store API (`FileStore.loadDocument()`) is async. For the
 * hot-path reads these sync helpers avoid the async conversion cost across
 * dozens of handlers. `savePRDSync` is kept sync so callers do not need to
 * be converted to async; the underlying Markdown write is atomic (temp-file
 * rename) just like the FileStore.
 *
 * @module web/server/prd-io
 */

import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
  statSync,
  readdirSync,
} from "node:fs";
import { join } from "node:path";
import type { PRDDocument } from "./rex-gateway.js";
import { SCHEMA_VERSION, isCompatibleSchema, serializeDocument, parseDocument, PRD_TREE_DIRNAME } from "./rex-gateway.js";

/** Primary Markdown PRD file. */
const PRD_MD_FILENAME = "prd.md";

/** Pattern for branch-scoped Markdown PRD companion files. */
const BRANCH_MD_PRD_RE = /^prd_(.+)_(\d{4}-\d{2}-\d{2})\.md$/;

/** Subdirectory for ephemeral server-generated artifacts. */
export const PRD_CACHE_DIR = ".cache";

/** Path to the ephemeral JSON cache inside the rex directory. */
export const PRD_CACHE_JSON = "prd.json";

function prdMdPath(rexDir: string): string {
  return join(rexDir, PRD_MD_FILENAME);
}

function cachePRDPath(rexDir: string): string {
  return join(rexDir, PRD_CACHE_DIR, PRD_CACHE_JSON);
}

/**
 * Discover branch-scoped `prd_{branch}_{date}.md` companion files.
 * Returns filenames sorted lexicographically (excludes `prd.md` and lock files).
 */
export function discoverMarkdownPRDFiles(rexDir: string): string[] {
  try {
    return readdirSync(rexDir)
      .filter((name) => BRANCH_MD_PRD_RE.test(name))
      .sort();
  } catch {
    return [];
  }
}

/** Check whether a readable PRD exists (folder tree primary, Markdown + legacy JSON fallback). */
export function prdExists(rexDir: string): boolean {
  // Primary: folder-tree backend (.rex/prd_tree/)
  const treeRoot = join(rexDir, PRD_TREE_DIRNAME);
  if (existsSync(treeRoot)) {
    try {
      // Treat the tree as present only when it actually contains items
      // (an empty directory shouldn't fool the data manifest).
      if (readdirSync(treeRoot).some((name) => !name.startsWith("."))) {
        return true;
      }
    } catch {
      // Fall through
    }
  }
  // Cache fallback (server-generated)
  if (existsSync(join(rexDir, PRD_CACHE_DIR, PRD_CACHE_JSON))) return true;
  // Legacy Markdown
  if (existsSync(prdMdPath(rexDir))) return true;
  // Legacy fallback: accept prd.json written by older code or REST routes
  return existsSync(join(rexDir, "prd.json"));
}

/**
 * Load the PRD document synchronously.
 *
 * Fast path: read from `.rex/.cache/prd.json` (generated by `ndx start`).
 * Fallback: parse `.rex/prd.md` directly (server not running, or cache absent).
 */
export function loadPRDSync(rexDir: string): PRDDocument | null {
  // Fast path — use the ephemeral cache written by the server at boot
  const cachePath = cachePRDPath(rexDir);
  if (existsSync(cachePath)) {
    try {
      const doc = JSON.parse(readFileSync(cachePath, "utf-8")) as PRDDocument;
      if (isCompatibleSchema(doc.schema)) return doc;
      console.warn(
        `[prd-io] Incompatible PRD schema in cache: found "${doc.schema ?? "(missing)"}",` +
        ` expected "${SCHEMA_VERSION}". Falling back to prd.md.`,
      );
    } catch {
      // Cache corrupt — fall through to direct parse
    }
  }

  // Second fallback — parse prd.md directly (no server running, or cache absent)
  const mdPath = prdMdPath(rexDir);
  if (existsSync(mdPath)) {
    try {
      const parsed = parseDocument(readFileSync(mdPath, "utf-8"));
      if (!parsed.ok) {
        console.warn(`[prd-io] Failed to parse prd.md: ${parsed.error.message}`);
      } else {
        const doc = parsed.data;
        if (!isCompatibleSchema(doc.schema)) {
          console.warn(
            `[prd-io] Incompatible PRD schema in prd.md: found "${doc.schema ?? "(missing)"}",` +
            ` expected "${SCHEMA_VERSION}". Run "rex validate" to check your PRD.`,
          );
        } else {
          return doc;
        }
      }
    } catch {
      // Fall through to legacy JSON
    }
  }

  // Third fallback — legacy prd.json (written by REST routes or older code)
  const legacyPath = join(rexDir, "prd.json");
  if (!existsSync(legacyPath)) return null;
  try {
    const doc = JSON.parse(readFileSync(legacyPath, "utf-8")) as PRDDocument;
    if (!isCompatibleSchema(doc.schema)) {
      console.warn(
        `[prd-io] Incompatible PRD schema in prd.json: found "${doc.schema ?? "(missing)"}",` +
        ` expected "${SCHEMA_VERSION}". Run "rex validate" to check your PRD.`,
      );
      return null;
    }
    return doc;
  } catch {
    return null;
  }
}

/**
 * Save a PRD document.
 *
 * Writes to `prd.md` (the Markdown source of truth) and also refreshes the
 * ephemeral cache so in-process `loadPRDSync` calls see the update immediately.
 */
export function savePRDSync(rexDir: string, doc: PRDDocument): void {
  // Write Markdown source of truth
  writeFileSync(prdMdPath(rexDir), serializeDocument(doc), "utf-8");
  // Keep cache in sync so loadPRDSync reads the latest state
  try {
    const cacheDir = join(rexDir, PRD_CACHE_DIR);
    mkdirSync(cacheDir, { recursive: true });
    writeFileSync(join(cacheDir, PRD_CACHE_JSON), JSON.stringify(doc, null, 2) + "\n", "utf-8");
  } catch {
    // Cache write failure is non-fatal — the cache will be refreshed by the watcher
  }
}

/** Resolve the path to `prd.md` in the given rex directory. */
export function prdPath(rexDir: string): string {
  return prdMdPath(rexDir);
}

/**
 * Return the latest modification time across `prd.md` and companion files (ms).
 * Returns 0 if no PRD files exist. Used by the data watcher for live-reload polling.
 */
export function prdMaxMtimeMs(rexDir: string): number {
  let max = 0;

  // Walk folder-tree (primary)
  const treeRoot = join(rexDir, PRD_TREE_DIRNAME);
  max = Math.max(max, walkMaxMtimeMs(treeRoot));

  // Stat primary prd.md
  try {
    const mtime = statSync(prdMdPath(rexDir)).mtimeMs;
    if (mtime > max) max = mtime;
  } catch {
    // File absent — skip
  }

  // Stat any branch-scoped prd_*.md companion files
  for (const filename of discoverMarkdownPRDFiles(rexDir)) {
    try {
      const mtime = statSync(join(rexDir, filename)).mtimeMs;
      if (mtime > max) max = mtime;
    } catch {
      // Skip unreadable files
    }
  }

  // Legacy fallback: also check prd.json (written by REST routes or older code)
  try {
    const mtime = statSync(join(rexDir, "prd.json")).mtimeMs;
    if (mtime > max) max = mtime;
  } catch {
    // File absent — skip
  }

  return max;
}

/** Recursively scan `dir` for the latest mtime across files and directories. */
function walkMaxMtimeMs(dir: string): number {
  let max = 0;
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return 0;
  }
  try {
    const dirMtime = statSync(dir).mtimeMs;
    if (dirMtime > max) max = dirMtime;
  } catch {
    // ignore
  }
  for (const name of entries) {
    const full = join(dir, name);
    let info;
    try {
      info = statSync(full);
    } catch {
      continue;
    }
    if (info.isDirectory()) {
      const sub = walkMaxMtimeMs(full);
      if (sub > max) max = sub;
    } else if (info.mtimeMs > max) {
      max = info.mtimeMs;
    }
  }
  return max;
}
